name: Code Quality
run-name: Code Quality
on: [push, pull_request]
jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          activate-environment: test-env
          environment-file: environment.yml
      - name: Check Formatting
        run: ruff format --check
      - name: Check Lint
        run: ruff lint
      - name: Run Tests with coverage
        run: python -m coverage run -m unittest discover

      
            