name: Lint and Format

on: 
  push:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths-ignore: # Pushes that include only these changed files won't trigger actions
      - "**/README.md"
      - "**/.gitignore"
      - "**/doc/*"

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          activate-environment: test-env
          environment-file: environment.yml
      - name: Install Ruff
        run: mamba install -y -c conda-forge ruff 
      - name: Check Formatting
        run: ruff format --check
      - name: Check Lint
        run: ruff lint