name: Lint and Format

on: 
  push:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruff
        run: pip install ruff 
      - name: Check Formatting
        run: ruff format --check
      - name: Check Lint
        run: ruff check .