name: Tests

on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths-ignore: # Pushes that include only these changed files won't trigger actions
      - "**/README.md"
      - "**/.gitignore"
      - "**/doc/*"

jobs:
    auto-tests:
        name: Auto Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Miniconda
              uses: conda-incubator/setup-miniconda@v3.0.4
              with:
                mamba-version: "*"
                channels: conda-forge,defaults
                activate-environment: test-env
                environment-file: environment.yml
            - name: Install coverage
              run: mamba install -y -c conda-forge coverage
            - name: Run Tests with coverage
              run: python -m coverage run -m unittest discover