name: Tests

on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths-ignore: # Pushes that include only these changed files won't trigger actions
      - "**/README.md"
      - "**/.gitignore"
      - "**/doc/*"

jobs:
    auto-tests:
        name: Auto Tests
        runs-on: ubuntu-latest
        defaults:
            run:
              shell: bash -el {0}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # Setup Conda Env using Cache if available
            - name: Setup Mambaforge
              uses: conda-incubator/setup-miniconda@v3
              with:
                miniforge-variant: Mambaforge
                miniforge-version: latest
                activate-environment: test-env
                use-mamba: true
            - name: Get Date
              id: get-date
              run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache Conda env
              uses: actions/cache@v3
              with:
                path: ${{ env.CONDA }}/envs
                key:
                  conda-${{ runner.os }}--${{ runner.arch }}--${{steps.get-date.outputs.today }}-${{hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER}}
              env:
                # Increase this value to reset cache if etc/example-environment.yml has not changed
                CACHE_NUMBER: 0
              id: cache
            - name: Update environment
              if: steps.cache.outputs.cache-hit != 'true'
              run:
                mamba env update -n test-env -f environment.yml

            # Run Tests
            - name: Install coverage
              run: mamba install -y -c conda-forge coverage
            - name: Run Tests with coverage
              run: coverage run -m unittest discover
            - name: Generate Coverage Report
              run: coverage xml -o coverage.xml
            - name: Add coverage report to PR
              uses: orgoro/coverage@v3.1
              with:
                  coverageFile: coverage.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  thresholdAll: 0.8
                  thresholdNew: 0.9
                  thresholdModified: 0.9
