name: Tests

on: 
  push: # REMOVE THIS AFTER DEBUGGING GH ACTIONS
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths-ignore: # Pushes that include only these changed files won't trigger actions
      - "**/README.md"
      - "**/.gitignore"
      - "**/doc/*"

jobs:
    auto-tests:
        name: Auto Tests
        runs-on: ubuntu-latest
        defaults:
            run:
              shell: bash -el {0}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Miniconda
              uses: conda-incubator/setup-miniconda@v3.0.4
              with:
                mamba-version: "*"
                channels: conda-forge,defaults
                activate-environment: test-env
                environment-file: environment.yml
            - name: Install coverage
              run: mamba install -y -c conda-forge coverage
            - name: Run Tests with coverage
              run: python -m coverage run -m unittest discover
            - name: Generate Coverage Report
              run: coverage xml -o coverage.xml
            - name: Add coverage report to PR
              uses: orgoro/coverage@v3.1
              with:
                  coverageFile: coverage.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  thresholdAll: 0.8
                  thresholdNew: 0.9
                  thresholdModified: 0.9
